### ISSUE TITLE
require 'mathn' breaks calculations

### ISSUE THREAD

**Issue by christianhellsten** [cardmagic/classifier#10]
require 'mathn' breaks calculations:

```
(10 / 23).class
=> Fixnum
require 'classifier'
(10 / 23).class
=> Rational
```

This means e.g. date calculations will break:

```
Date.civil(year, month, day)
=> ArgumentError: invalid date 
```

See:
http://blog.brightredglow.com/2008/1/17/evil-can-be-dangerous/

**Comment by cardmagic** [comment]
I've removed mathn thank you
