### ISSUE TITLE
Still having problems with ActiveRecord

### ISSUE THREAD

**Issue by masnick** [cardmagic/classifier#2]
Unfortunately the problem I was having before still isn't solved...here's the error I'm getting now: `/Library/Ruby/Gems/1.8/gems/classifier-1.3.3/lib/classifier/extensions/vector.rb:16:in`sum': undefined method `to_f' for []:Array (NoMethodError)`

**Comment by cardmagic** [comment]
Fixed in version 1.4.0 and above
