### ISSUE TITLE
Error at classification method

### ISSUE THREAD

**Issue by ghost** [cardmagic/classifier#20]
I am using sourceclassifier gem, but whenever i want to identify a piece of code an error pops out. From the stacktrace I understood that this happens in classifier 'classification' method.

Here is the full stacktrace:

from /Users/olegkiviljov/.rvm/gems/ruby-2.0.0-p247/gems/classifier-1.3.4/lib/classifier/bayes.rb:88:in `classify'
    from /Users/olegkiviljov/.rvm/gems/ruby-2.0.0-p247/gems/chrislo-sourceclassifier-0.2.3/lib/sourceclassifier.rb:19:in`identify'
    from experiment.rb:21:in `<main>'

I posted the same issue in sourceclassifier issues but with no avail. If someone could atleast tell me if it is a problem with sourceclassifier or with classifier, this would give me enough information to try and fix it myself.

**Comment by cardmagic** [comment]
sorry, I can't help you with that library
