### ISSUE TITLE
please tag releases in the repository

### ISSUE THREAD

**Issue by boutil** [cardmagic/classifier#30]
Hi,

Could you please tag commits corrsponding to releases in the repositories? The last gem version is 1.3.5 but it is not easy to spot which commit it corresponds to. This would allow also automatic creation of tarballs from the tag, useful for packagers for distributions.

Thanks.

Cédric

**Comment by cardmagic** [comment]
Fixed in https://github.com/cardmagic/classifier/releases/tag/v1.4.0
