### ISSUE TITLE
please continue to export tests in the gem

### ISSUE THREAD

**Issue by boutil** [cardmagic/classifier#31]
Hi,

I noticed that 1.3.5 gem version doesn't include the tests, whereas they were present in the 1.3.4 version. Could you please continue to include them? For Debian packages, we try to use the gem as the base of source package, and it is useful for our quality assurance that tests are present directly there.

Thanks a lot

Cedric

**Comment by cardmagic** [comment]
Fixed in version 1.4.0 thank you!
